Makefile, pkg/coreos/actuator_delete.go, pkg/coreos/actuator_reconcile.go
The `update-engine` and `locksmithd` units are now explicitly stopped which should help in effectively preventing undesired machine reboots. See also https://github.com/coreos/docs/commit/9bdc9ddd9b52fd7700617818d8b72cfd758bee88#diff-10a5984baf88a6d8832c4f852f2b685cL77-L85
Thanks @kayrus for spotting 💌 
```improvement user
The `update-engine` and `locksmithd` units are now explicitly stopped which should help in effectively preventing undesired machine reboots.
```
=> Explicitly disable update-engine and locksmithd

.ci/pipeline_definitions
I want to try out the kaniko oci builder as according to the cicd folks it should resolved the issue with dockerhub rate limits and will allow us to remove the images that are copied in GCR currently.
As the the `.ci/pipeline_definitions` is taken from the master branch, we need first to update the pipeline_definitions and then try to adapt the base images in another PR (that will be built using the kaniko oci builder).
```improvement operator
NONE
```
=> Switch to kaniko oci builder

go.mod, pkg/coreos/actuator_reconcile.go, pkg/coreos/actuator_test.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_delete.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_migrate.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_reconcile.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_restore.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_util.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/cloudinit/cloudinit.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/generator/generator.go, vendor/modules.txt
Accepts the flag `Transmit Unencoded`.
Needed for creation of bootstrap-tokens for machines introduced here: https://github.com/gardener/gardener/pull/3902
/area security
See https://github.com/gardener/gardener/issues/3898 and https://github.com/gardener/gardener/pull/3902
```other operator
Introduces new flag `TransmitUnencoded` which writes file content unencoded into the worker resource.
```
=> Support transmitUnencoded flag

pkg/coreos/actuator_reconcile.go, pkg/coreos/actuator_test.go, pkg/coreos/templates/containerd/run-command.sh.tpl, pkg/coreos/types.go
/area os
Enable support for containerd.
Fixes #26 
The usual bin directories  `/bin`, `/usr/bin` and `/usr/loca/bin` in Flatcar are read-only, therefore it is not possible to place symbolic links there to the containerd binaries which are installed in `/run/torcx/unpack/docker/bin`. Therefore this extension adds `/run/torcx/unpack/docker/bin` to the PATH in the containerd and kubelet environment.
As there is no support for `runcmd` in CoreOS/Flatcar, this behavior is achieved via a oneshot systemd service.
I have created an AWS 1.18.20 shoot cluster and run successfully several times the conformance tests from …
=> Enable support for containerd

Dockerfile
* upgrades busybox to fix CVE-2022-28391
/area os
/kind technical-debt
Updates the base image used for delivering the CoreOS/FlatCar extension to [Alpine 3.15.4](https://alpinelinux.org/posts/Alpine-3.12.12-3.13.10-3.14.6-3.15.4-released.html) which contains a fix for [CVE-2022-28391](https://security.alpinelinux.org/vuln/CVE-2022-28391).
```other user
- upgrades base image to Alpine 3.15.4 to fix CVE-2022-28391
```
=> update alpine base image to 3.15.4

pkg/coreos/actuator_test.go, pkg/coreos/templates/containerd/run-command.sh.tpl
/area os
/kind bug
Recent flatcar images has the logrotate binary not in `/usr/sbin` anymore, but in `/usr/bin`. Thus this PR extends the `run-command.service` (doing Containerd & Flatcar / Core OS related patches) to check for the alternate location of logrotate. If it finds the binary under `/usr/bin` it patches the path in `/etc/systemd/system/containerd-logrotate.service`.
Fixes #54
**Special notes for your reviewer**: -
```other operator
bugfix user 
fixes containerd-lograte unit for Flatcar images with logrotate in /usr/bin
```
=> Compatibility with logrotate in /usr/bin

.github/dependabot.yaml, .github/workflows/vendor_gardener.yaml
/area os
/kind technical-debt
/os suse-chost
Integrates the changes pushed to gardener-extension-os-gardenlinux by @Kostov6 and @ialidzhikov into the coreos/flatcar extension to have dependabot take care of up-to-date Gardener dependencies.
```other operator
NONE
```
=> Add dependabot to manage Gardener packages

CODEOWNERS
/area os open-source
At STACKIT, we offer flatcar as the primary OS for worker nodes. Hence, we rely on this extension.
As other interested parties faced out CoreOS/flatcar in their environments, we probably have the highest stakes in keeping this extension up-to-date.
To simplify things, this PR adds two codeowners from STACKIT (particular persons are not set in stone).
This allows us to formally assume responsibility for this repository.
TODO:
See https://gardener-cloud.slack.com/archives/C045DSWJZB9/p1711461148599709
I recall, that we cannot add contributors from outside SAP to the gardener org. With this, we cannot add STACKIT …
=> Add codeowners from STACKIT

.ci/pipeline_definitions
/area open-source
/kind cleanup
Pipelines were moved to dedicated OpenSource Concourse team, thus slack-cfg reference needs to be adjusted.
Fixes #
```other operator
```
=> Update slack-cfg used to publish release-notes

pkg/controller/operatingsystemconfig/coreos_reconcile.go
/area os
/kind bug
When the Gardener Node Agent for worker nodes is activated, either using the appropriate featuregate or using Gardener version v1.89.0 and above, the OperatingSystemConfig introduces some changes. One of these changes is, that files can now have a imageRef field. When this field is present, the file is extracted from a container image and not presented inline.
The reconcile is running into a panic in case of files with an imageRef field, because its trying to extract the inline data.
This small fix simply skips the content collection for these kind of files.
```bugfix operator
Skipping filecontent collection for files with imageRef in OperatingSystemConfigs to prevent a panic.
```
=> [release-v1.21] Fix filepath collection for files with `ImageRef`

pkg/controller/operatingsystemconfig/coreos_reconcile.go
/area os
/kind bug
When the Gardener Node Agent for worker nodes is activated, either using the appropriate featuregate or using Gardener version v1.89.0 and above, the OperatingSystemConfig introduces some changes. One of these changes is, that files can now have a imageRef field. When this field is present, the file is extracted from a container image and not presented inline.
The reconcile is running into a panic in case of files with an imageRef field, because its trying to extract the inline data.
This small fix simply skips the content collection for these kind of files.
```bugfix operator
Skipping filecontent collection for files with imageRef in OperatingSystemConfigs to prevent a panic.
```
=> [release-v1.20] Fix filepath collection for files with `ImageRef`

pkg/controller/operatingsystemconfig/coreos_reconcile.go
/area os
/kind bug
When the Gardener Node Agent for worker nodes is activated, either using the appropriate featuregate or using Gardener version v1.89.0 and above, the OperatingSystemConfig introduces some changes. One of these changes is, that files can now have a imageRef field. When this field is present, the file is extracted from a container image and not presented inline.
The reconcile is running into a panic in case of files with an imageRef field, because its trying to extract the inline data.
This small fix simply skips the content collection for these kind of files.
```bugfix operator
Skipping filecontent collection for files with imageRef in OperatingSystemConfigs to prevent a panic.
```
=> [release-v1.19] Fix filepath collection for files with `ImageRef`

pkg/controller/operatingsystemconfig/actuator.go, pkg/controller/operatingsystemconfig/actuator_test.go
/area control-plane
/kind bug
The extension disables the units for automatic updates without setting the `Enabled` to `false`.
Gardener enables the the units, if `Enabled` is false: [Code](https://github.com/gardener/gardener/blob/v1.90.0/pkg/nodeagent/controller/operatingsystemconfig/reconciler.go#L337) 
This Pull Request disables the auto-update units.
**Context**:
At Gardener `v1.90`, the Gardener node agent updates the `OperatingSystemConfig`s for the nodes and throws following errors within the node:
`"error":"failed applying changed units: unable to enable unit \"update-engine.service\"` 
```bugfix operator
Fixing the deactivation of the units responsible for automatic updates.
```
=> disable units for automatic updates

pkg/controller/operatingsystemconfig/actuator.go, pkg/controller/operatingsystemconfig/actuator_test.go
/area os
/kind bug
Cherry-pick of https://github.com/gardener/gardener-extension-os-coreos/pull/112
```bugfix operator
Fixing the deactivation of the units responsible for automatic updates.
```
=> [v1.22] #112 set enable to false

README.md
The url for builds has changed, this fixes the status badge respective link in the README.md
=> fix(README): adjust concourse link

Makefile
/area os
/kind technical-debt
Changes the Makefile to use docker buildx to build container images for this extensions so that we can build images for multiple architectures with linux/amd64 being the default.
```other operator
Container images for the coreos extension are now built with Docker buildx to enable cross-platform builds and default to the `linux/amd64` architecture.
```
=> use buildx to build docker images

pkg/controller/operatingsystemconfig/actuator.go, pkg/controller/operatingsystemconfig/actuator_test.go, pkg/controller/operatingsystemconfig/templates/11-exec_config.conf
/area os
Prevent `11-exec_config.conf` from being accidentally deleted by gardener-node-agent.
Fixes #
```noteworthy operator
The `11-exec_config.conf` is now being reconciled by the `Provision` step of the gardener-node-agent
```
=> Add `11-exec_config.conf` to gardener-node-agent reconcile

.ci/pipeline_definitions
/area os
Adds Vincinator as responsible for this repository in component-descriptor.
```other operator
NONE
```
=> Add vincinator as responsible

CODEOWNERS
/area os open-source
We would like to add @nschad as an additional codeowner from STACKIT to this repository. Similar to @dergeberl and @timebertt in #96.
Related to ##198
```other operator
NONE
```
=> Add additional codeowners from STACKIT

.github/workflows/head-update.yaml
/area os
/kind regression
Head update jobs for merged pull requests fail as required permissions are missing, see [failed workflow](https://github.com/gardener/gardener-extension-os-coreos/actions/runs/17035112731)
=> Fix head-update gh action

CODEOWNERS
/area os
/kind cleanup
@dergeberl and @nschad are maintainers on our side. I'm no longer directly involved in the CoreOS/Flatcar topics.
Remove myself from the CODEOWNERS file of this extension to have more precise responsibilities and less noise in my notifications inbox.
Fixes #
```other operator
NONE
```
=> Remove timebertt from `CODEOWNERS`

.github/workflows/build.yaml, .github/workflows/head-update.yaml, .github/workflows/release.yaml
/area dev-productivity
/kind regression
Should potentially fix the permission problem in the GH Workflows. (Needs to be verified)
I just looked at https://github.com/gardener/gardener-extension-provider-aws/pull/1453 and https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/398
Fixes #
```other operator
NONE
```
=> fix: required permissions for build & release workflow
